### ISSUE TITLE
How to hide the untracked files in files？

### ISSUE THREAD

**Issue by hzwangzi123456** [jesseduffield/lazygit#982]
How to hide the untracked files in files？

**Comment by glvr182** [comment]
You mean like gitignore?

**Comment by jesseduffield** [comment]
This can be done at the repo level with the git config. Closing due to staleness

**Comment by epheien** [comment]
need toggle hide untracked files feature

**Comment by jesseduffield** [comment]
@epheien do you mean from within lazygit?

**Comment by epheien** [comment]
> @epheien do you mean from within lazygit?

yes, I need not change git config and simply toggle show / hide untracked files, for example:
`git status -uno`

Some git client has this feature, such as Fork.app on macOS.

**Comment by jesseduffield** [comment]
I've updated the issue description for this use case

**Comment by cas--** [comment]
I was just trying out lazygit and this was an immediate issue since I had been testing npm apps in a repo but not made any commits so node_modules was still hanging around and the entire listing for that directory made the Files panel unusable upon first opening. 

![image](https://user-images.githubusercontent.com/606038/152974670-97eb6aac-318f-4f1d-8f92-52931b79d816.png)

I thought that having a hide untracked files setting would be the solution for me however there are perhaps some UX improvements that could help as well. 

Firstly I found the discussion in #1712 about how to navigate panels and it was non-obvious to me to use <kbd>Enter</kbd> to collapse a dir, I kept trying arrow keys. Also how do you navigate to top or bottom of the file panel since <kbd>PgUp</kbd> or <kbd>PgDn</kbd> navigates in the change panel.

One small improvement might be for untracked directories (or very long directory listings) to be collapsed by default? 

![image](https://user-images.githubusercontent.com/606038/152976144-6baa05a5-b846-434b-8c62-d349097a9656.png)

A further improvement would be to sort by tracked first and prefixing dirs with `??` or `M`. This would emulate the short git status. (side-note I feel dot prefix files really should sort first):

![image](https://user-images.githubusercontent.com/606038/152975282-e405ed91-6ae8-4334-8e50-b4c5ceedf6b8.png)

I hope this helps in deciding what to do with this issue

**Comment by dcd-arnold** [comment]
I would like to add that I would like the option to add the untracked file I see.

**Comment by mark2185** [comment]
> I would like to add that I would like the option to add the untracked file I see.

Add it as in "stage it"? Pressing `space` should do it.

**Comment by dcd-arnold** [comment]
hi @mark2185,
thanks for getting back to me. I have set
```
[status]
showuntrackedfiles = no
```
in my git config. I don't want to see untracked files in `git status` on command line. I add the files I need (seeing all files on the commandline with `ls`). 

However, I do not see untracked files in `lazygit`. My guess is, `lazygit` picks that setting up. But I don't see all or untracked files in `lazygit`, hence I can't add them on demand. I leave `lazygit`, add the files and start `lazygit` again to continue to work on the commit. I would like to able to switch view of (un-)tracked files within `lazygit` so I don't have to leave to the command line an back. I hope that explanation clears things up a bit.

**Comment by mark2185** [comment]
Oh yes, that clears things up quite a bit.

@jesseduffield maybe the `showuntrackedfiles` setting should only change the initial state of the filter? 

Those with said setting will have the filter `Show only staged files`, others will have it set to `no filter`, and the `Files` pane should always show all the files and then filter them out if needed?

**Comment by jesseduffield** [comment]
I agree about showuntrackedfiles determining the initial state, but in this case `Show only staged files` won't do because we still want to show unstaged, tracked files.

**Comment by mark2185** [comment]
Oh yeah, forgot about that tiny detail.

Well then, having the filters togglable? I know toggles aren't yet a feature, but hey.
```
[X] Show staged files
[X] Show unstaged files
[X] Show tracked files
[X] Show untracked files
```

**Comment by jesseduffield** [comment]
I'm thinking we could have a 'show staged / show unstaged / show all' option as well as a separate toggle for 'show untracked'.
So we'd have this logic:
|         | staged         | unstaged       | all            |
|----------------|----------------|----------------|----------------|
| **show untracked** | hide untracked | show untracked | show untracked |
| **hide untracked** | hide untracked | hide untracked | hide untracked |

Where the column headers are for the staged/unstaged/all option and the row headers are for the 'show untracked' toggle, and the cells in the middle describe whether we actually show untracked files given a combination of the two options.

**Comment by mark2185** [comment]
Yeah, that makes more sense. :smile:

**Comment by jesseduffield** [comment]
Now we just need that toggle feature!

**Comment by mark2185** [comment]
I say we wait for `lazydocker` to get that and then steal it. :full_moon_with_face:

**Comment by jesseduffield** [comment]
hahaha

**Comment by all500234765** [comment]
But what about hiding specific untracked folders that won't be commited in any case? Or hiding only untracked files inside a specific folder?
For example: I have a project that I am working on, and I have lots of testing data, meta files, png, txt, etc... It can pile up to a several GBs with thousands of files. Navigating with this pile to stage specific file is quite hard. And most of the time my day starts with me closing all folders except source code, since it has no similar problems (:

I have following structure:

ImportantFolderRoot/ImportantFolder1/,,,
ImportantFolderRoot/ImportantFolder2/...
ImportantFolderRoot/ImportantFile1
ImportantFolderRoot/ImportantFile2
ImportantFolderRoot/UnstagedTestingFile1
ImportantFolderRoot/...
ImportantFolderRoot/UnstagedTestingFolder/...

and so on.

**Comment by jesseduffield** [comment]
@all500234765 would that not be a good candidate for inclusion in the gitignore file?

**Comment by all500234765** [comment]
Then it will have merging issues because those files are local and git repo shouldn't know anything about them until commited

**Comment by Wrayos** [comment]
Chiming in to describe my use-case for this.  I store my config dotfiles in a bare repo at `~/.dotfiles`, and typically interact with it like `lazygit --git-dir="$HOME/.dotfiles/" --work-tree="$HOME"`.  Given that the entire home directory is the worktree, I have `status.showUntrackedFiles` disabled for this repo.

Whenever I want to add a new file to the repo I find myself reaching for regular git to add it as I can't find a way to do that in lazygit.

I don't necessarily need or even want a toggle to show untracked files as that will certainly break things in my situation as it contains _every file in my home directory_.  I simply need a way to add a currently untracked file - whether by providing a fill path or navigating to it and selecting it somehow, the mechanism wouldn't matter a whole lot to me.  It would just let me not reach for raw git.

**Comment by mark2185** [comment]
>  It would just let me not reach for raw git.

Would running a custom command through `:` suffice? 

Just `:git add <file>`, but just to point out that there is no autocompletion.

**Comment by Wrayos** [comment]
I sort of assumed that wouldn't give me a lot of benefits because I thought I'd need to add in the whole `--git-dir="$HOME/.dotfiles/" --work-tree="$HOME"` again to that command..  But it turns out I was wrong.

`:git add ~/test` does indeed work as expected - so this gets me basically where I wanted, just without ideal UX.  Thanks a bunch for the suggestion

**Comment by AckslD** [comment]
> as well as a separate toggle for 'show untracked'.

I would love this! I often find myself in cases where I only want to see tracked files but I don't yet want to add the untracked files to gitignore.

**Comment by melMass** [comment]
I'm personally doing this but LazyGit needs to be restarted to refresh, could I refresh lazyy without restarting it?:

```yaml
customCommands:
  - key: "u"
    command: "git config status.showUntrackedFiles {{.Form.Value}}"
    context: "global"
    prompts:
      - type: "menu"
        title: "Show untracked?"
        key: "Value"
        options:
          - value: "yes"
            name: "Yes"
            description: "Show untracked files"
          - value: "no"
            name: "No"
            description: "Hide untracked files"
```

**Comment by jesseduffield** [comment]
@melMass try pressing shift+R from the files view after running that command, it should refresh the files and that should make use of the new git config value.

**Comment by melMass** [comment]
Thanks @jesseduffield ! The values of my custom commands were wrong (it's either `normal` or `all` not `yes`), but I still can't seem to be able to refresh the file list (I tried shift R and r which is what the help shows):

```yaml
customCommands:
  - key: "u"
    command: "git config status.showUntrackedFiles {{.Form.Value}}"
    context: "global"
    prompts:
      - type: "menu"
        title: "Show untracked?"
        key: "Value"
        options:
          - value: "normal"
            name: "Normal"
            description: "Show untracked files"
          - value: "all"
            name: "All"
            description: "Show untracked files (individual files in directories)"
          - value: "no"
            name: "No"
            description: "Hide untracked files"
```

**Comment by tbena** [comment]
Any updates on this? The solution in the comment above works but feels hacky and requires re-opening lazygit. 
I also tried both r and shift+r from the help and it did not work.

**Comment by elig0n** [comment]
Is this planned or too difficult to achieve?

**Comment by JamesMowery** [comment]
I'm also following this. Would really like this to be a feature. :)

**Comment by pidgeon777** [comment]
Me too. Maybe add this in the `<c-b> Filter files by status` submenu? Actually it has:

- `s Show only staged files`
- `u Show only unstaged files`
- `r Reset filter`
- `Cancel`

I think this sub-menu could be a good choice to store the new `hide/show untracked file` option.

**Comment by MartyMcFlyInTheSky** [comment]
I would also like this feature. When working on dotfiles it seems quite natural to have
```

[status]
	showUntrackedFiles = no
```

but how then am I supposed to add  a new file from within lazygit? I think atm it's not possible without invoking the inline CLI.

**Comment by pidgeon777** [comment]
Are we talking about this new feature recently implemented?:

https://github.com/jesseduffield/lazygit/pull/4024

**Comment by tbena** [comment]
> Are we talking about this new feature recently implemented?:
> 
> [#4024](https://github.com/jesseduffield/lazygit/pull/4024)

No. While it is a step in the right direction to have it natively in LazyGit it still has exactly the same caveats as in the solution by @melMass
It still only takes effect after closing and re-opening LazyGit and shift-r does not solve the issue.

**Comment by melMass** [comment]
@pidgeon777 Awesome I wasn't aware of this PR!!!

@tbena I just tried it (`<C-b>` -> show only tracked) and it works fine without restart for me (lazygit 0.45.2)

I think this issue can be closed now

**Comment by JamesMowery** [comment]
@melMass I don't think this is correct. I'm not seeing a toggle/filter to view **untracked** files. Unless I'm missing it.

This issue is specifically because we need the ability to view and hide **untracked** files within Lazygit. I only see a filter to show tracked files only. This is (probably) because we are using a bare git repo to manage our .config files.

**Comment by melMass** [comment]
@JamesMowery Unless I'm dumb (probable 😅 ) this is it no? At least that was why I was sub to this issue

https://github.com/user-attachments/assets/a5276080-8db7-4501-bbb4-0a08931051a2

**Comment by AckslD** [comment]
That's awesome, I'm still on 0.44.1 (from nix 24.11) and hadn't noticed!

**Comment by JamesMowery** [comment]
@melMass I'm not seeing any difference whatsoever. Here's a screen recording showing what I'm seeing:

https://github.com/user-attachments/assets/ee8ba3d8-d91e-497f-94d1-3c74c158cfc6

**Comment by melMass** [comment]
That's a diffferent thing, for this the solution here https://github.com/jesseduffield/lazygit/issues/982#issuecomment-2030949389 should work fine, you could probably call the lazygit display option as part of the command too so that it both refreshes live in lazygit and affects the git config.

I much prefer the native implementation that just filters it's own "objects" rather than editing the git config. I guess you could open a dedicated issue to have an option to apply this filter to the git config too. I think most would want the display only solution.

**Comment by JamesMowery** [comment]
@melMass But this issue is specifically for adding an option to show/hide **_untracked_** files.

The referenced comment you posted is only a filter for tracked files. I don't see how this issue is solved. I know you might prefer that solution, but this issue is specifically for the visibility for **untracked files**. So this issue is not resolved in my opinion.

**Comment by melMass** [comment]
Ah my bad I misread your screen record, the option is not a toggle, it's "tracked" or "unstaged", I guess it's a bit confusing in the naming I agree, but unstaged is also untracked as seen in my recording

**Comment by melMass** [comment]
Yeah it's not perfect, it works for my needs personally but I think it would be better if all these filters were toggles not `only`...

**Comment by MartyMcFlyInTheSky** [comment]
Even with the newest version it still doesn't do the trick for me.

The problem is that I work with a git repo to manage my dotfiles, and this repo lives in $HOME directly. To make this usable, I exclude all the non-tracked files from my gitstatus:

_.git/config_

```
[status]
	showUntrackedFiles = no
```

No matter what I filter, lazygit will always just display the tracked files. So how can I add new file the tracked files? Right now I can't from within lazygit, I need to go out and use `git add ...` manually. I'd prefer if there was an option to do this from within lazygit, especially since I'm using lazygit with neovim and I would have to quit it as well (or put it to background).

I'm not suggesting that you should show _all_ untracked files, that would completely clutter the view. But maybe one could apply that to just one folder? I think that could be really awesome.

**Comment by jesseduffield** [comment]
This PR should do the trick: https://github.com/jesseduffield/lazygit/pull/4226

**Comment by JamesMowery** [comment]
> This PR should do the trick: [#4226](https://github.com/jesseduffield/lazygit/pull/4226)

Amazing! Look forward to trying this out!!!

**Comment by yanshay** [comment]
For me, on 0.45.2 filtering to show only tracked files, shows only **modified** tracked files (so those candidate for commit with `git add -u`). It doesn't show unchanged tracked files.

**Comment by tobixx** [comment]
One little wish to add here while the status is still open: a config setting would be really helpful (I didn't find anything related in the documentation).

Reasoning: I don't want to rely on the git setting `showUntrackedFiles` because it reminds in the terminal that I still have something to do if I find the time for it. But in lazygit I only want to see the tracked files, to concentrate on work in progress, without typing `CTRL-b`, `CTRL-b`, `t` every time I enter lazygit (double `CTRL-b` to escape the tmux binding).

So something like the following in the `gui` section:
```
  # Intial git status filter to apply by default
  # Options are:
  # - 'staged': show only staged files
  # - 'unstaged': show only unstaged files
  # - 'tracked': show only tracked files
  # - 'untracked': show only untracked files
  # - 'all': (default) show all files (no filter) 
  statusFilter: tracked
```

**Comment by stefanhaller** [comment]
> One little wish to add here while the status is still open:

I think it's only open because nobody bothered to close it. From the discussion above, it sounds to me like #4226 addressed the need, so I'll close it now.

> Reasoning: I don't want to rely on the git setting `showUntrackedFiles` because it reminds in the terminal that I still have something to do if I find the time for it.

I don't understand what you mean. Can you explain again why you want different settings for cli git vs. lazygit?

**Comment by sedm0784** [comment]
> > Reasoning: I don't want to rely on the git setting `showUntrackedFiles` because it reminds in the terminal that I still have something to do if I find the time for it.
> 
> I don't understand what you mean. Can you explain again why you want different settings for cli git vs. lazygit?

Like @tobixx, I would also like lazygit to have a separate setting for this. I use lazygit for adding files to/removing them from the index, (running a new instance each time&mdash;I don't have it running all the time), but I still mainly use git status for just viewing current status.

I sometimes have untracked files in my repository for a medium-to-long period of time, and I have git configured to show untracked files by default so I never forget them.

In lazygit this is very awkward for three reasons:

1. Unlike on the command line, when I first open lazygit, every file in an entirely untracked folder is displayed. Before you added the command to hide them I had to manually go to each untracked folder and close it every time I ran lazygit.

2. Even if untracked folders were collapsed by default, because lazygit is a TUI, in order to navigate to entries below them I have to manually step over them. On the command line they are *only* visual: I can ignore them and they don't affect interactions in any way.

3. This is more minor, but because of the rest of the UI takes up space, each line lost to an untracked file/folder I'm currently not interested in is more impactful.

As such, the way I use it, pretty much every time I open lazygit (generally many times a day) I have to manually type `<C-B>t` to hide untracked files. It's only two keystrokes, so it's not that much of an imposition, but a config setting would still be vastly preferable for me.
